name: DogDataAuto
on:
  workflow_dispatch:
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: pip install requests beautifulsoup4 pandas lxml
      - name: Run
        run: python main.py
      - name: Save
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@noreply.com'
          git add *.csv
          git commit -m "Update" || exit 0
          git push

