name: DogDataStarterPackAuto

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 09:00 KST
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3 # Use v3 for stability
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread

      - name: Run Python Script
        env:
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: python main.py
